### ISSUE TITLE
Using prebind_url user not showing contact list after reconnecting.

### ISSUE THREAD

**Issue by nikksbagul** [jcbrand/converse.js#683]
Hello,

I'm trying to use prebind_url (with authentication set to prebind and auto_reconnect set to true) with Converse 0.10. My issue is after reconnecting not showing any contacts to user.

my initialization is

```
converse.initialize({
         allow_registration: false,
         include_offline_state: true,
         authentication: 'prebind',
         allow_logout: false,
         prebind_url: "https://10.1.1.59:8000/prebind/",
         show_controlbox_by_default: true,
         xhr_user_search: true,
         bosh_service_url: "https://10.1.1.59:7443/http-bind/",
         show_only_online_users: true,
         allow_contact_requests: true,
         auto_list_rooms: true,
         auto_subscribe: false,
         auto_reconnect: true,
         hide_muc_server: true,
         debug: true,
         prebind: true,
         roster_groups: true,
         animate: true,
         jid: 'nikhilba@devtest',
         sid: '6xel80wawk',
         rid: '2981289',
     });
```

**Comment by jcbrand** [comment]
This is a known issue that is now fixed in master (not released yet).

The master branch is currently stable, so you can try to use it instead.

**Comment by nikksbagul** [comment]
Still getting this issue in master branch. Please upgrade dist/converse.js file. I'm only use this file.

**Comment by jcbrand** [comment]
You can run `make dist` to generate the dist file.
