### ISSUE TITLE
keepalive not working with anonymous authentication

### ISSUE THREAD

**Issue by Selaron** [jcbrand/converse.js#721]
The keepalive feature that maintains XMPP sessions across page reloads and navigation does not work with
authentication: 'anonymous',
jid: 'myserver.tld/myresource',
bosh_service_url: 'https://myserver.tld/http-bind/',
keepalive: true,
...

Thus on each navigation or page reload the chatbox does a new anonymous authentication against the server, loosing all open chat windows, message history etc.

When removing the 'authentication' and 'jid' attributes from the initializer and authenticating using a regular account, keepalive works fine.

BTW: the online anonymous auth demo currently is non functional: https://conversejs.org/demo/anonymous.html

**Comment by jcbrand** [comment]
> BTW: the online anonymous auth demo currently is non functional: https://conversejs.org/demo/anonymous.html

Woops. Works now again.

BTW, keepalive also seems to work there. So this might be an XMPP server issue on your side.

**Comment by jcbrand** [comment]
> BTW: the online anonymous auth demo currently is non functional: https://conversejs.org/demo/anonymous.html

Woops. Works now again.

BTW, keepalive also seems to work there. So this might be an XMPP server issue on your side.

**Comment by jcbrand** [comment]
> BTW: the online anonymous auth demo currently is non functional: https://conversejs.org/demo/anonymous.html

Woops. Works now again.

BTW, keepalive also seems to work there. So this might be an XMPP server issue on your side.

**Comment by jcbrand** [comment]
> BTW: the online anonymous auth demo currently is non functional: https://conversejs.org/demo/anonymous.html

Woops. Works now again.

BTW, keepalive also seems to work there. So this might be an XMPP server issue on your side.

**Comment by jcbrand** [comment]
> BTW: the online anonymous auth demo currently is non functional: https://conversejs.org/demo/anonymous.html

Woops. Works now again.

BTW, keepalive also seems to work there. So this might be an XMPP server issue on your side.

**Comment by jcbrand** [comment]
> BTW: the online anonymous auth demo currently is non functional: https://conversejs.org/demo/anonymous.html

Woops. Works now again.

BTW, keepalive also seems to work there. So this might be an XMPP server issue on your side.

**Comment by jcbrand** [comment]
Actually, I was wrong. Looking at the JID being generated, it's a new JID for each page reload.

**Comment by jcbrand** [comment]
I took a quick look at the relevant code and saw what needed to be done.

Fixed now in master (together with [this strophe.js commit](https://github.com/strophe/strophejs/commit/b82171f81db469050bf55fa5394b3283c9b3d3bd)).

**Comment by Selaron** [comment]
Thanks for looking into it that quickly.
For me it still doesn't work: I Checked out master, issued "make dist", adjusted dome/anonymous.html to use ../dist/converse.js and this still gets a new JID on every page load.

**Comment by jcbrand** [comment]
Dammit. It was working, but I see now on the live site that it's recreating the session again.

**Comment by Selaron** [comment]
On your live site, is it master or release 2.0.1 (w/o #721 fix) running?

**Comment by jcbrand** [comment]
Oh, so that's why it's working there. It's 2.0.1. I forgot that the fix is not included in the 2.0.1 release.

Well, then it's maybe something like your strophe.js version. Try`make clean && make dist` to fetch all dependencies anew and then see if that helps.

**Comment by Selaron** [comment]
I debugged into it and found my convers.js to use the most recent version of strophe.js. It got really close to restore the session, but there's one comparison in strophe.js that fails. Left a comment to
[your strophe.js commit](https://github.com/strophe/strophejs/commit/b82171f81db469050bf55fa5394b3283c9b3d3bd) .

**Comment by jcbrand** [comment]
Good that you debugged, I think you found a bug. I've updated strophe and package.json. Can you please confirm whether it's working now?

**Comment by Selaron** [comment]
Yes it works now.
