### ISSUE TITLE
OTR can't start, Base64Str TypeError

### ISSUE THREAD

**Issue by ignatdoc** [jcbrand/converse.js#848]
Hello.

I have installed converseJS to my server, thank you very much for such a great client! It is the best from JS Web clients I have tried :)

So I get one problem... Can't understand how to get OTR to work. In debug mode I get Base64Str TypeError errors as undefined. Should I add some other libs and how? (bigint.js, crypto.js and etc?)
I took converse.js from src dir for my website.

Thank you !

**Comment by jcbrand** [comment]
You need to take converse.js from the `dist` directory. Or you can load it via the CDN: https://cdn.conversejs.org/3.0.1/dist/converse.min.js

**Comment by ignatdoc** [comment]
Sure I have done that, but I get an error in debug about Base64Str TypeError

**Comment by jcbrand** [comment]
Then set `debug` to true and paste the full error here please.

**Comment by ignatdoc** [comment]
TypeError: base64Str is undefined[Learn More]  converse.js:59687:17
	C_enc.Base64.parse https://someserver.com/_assets/conversejs/dist/converse.js:59687:17
	DSA.parsePrivate https://someserver.com/_assets/conversejs/dist/converse.js:62553:13
	.overrides.ChatBox.getSession https://someserver.com/_assets/conversejs/dist/converse.js:64547:37
	wrappedOverride https://someserver.com/_assets/conversejs/dist/converse.js:43987:20
	apply https://someserver.com/_assets/conversejs/dist/converse.js:12950:12
	wrapper https://someserver.com/_assets/conversejs/dist/converse.js:17807:16
	.overrides.ChatBox.initiateOTR https://someserver.com/_assets/conversejs/dist/converse.js:64628:21
	wrappedOverride https://someserver.com/_assets/conversejs/dist/converse.js:43987:20
	apply https://someserver.com/_assets/conversejs/dist/converse.js:12948:22
	wrapper https://someserver.com/_assets/conversejs/dist/converse.js:17807:16
	.overrides.ChatBoxView.startOTRFromToolbar https://someserver.com/_assets/conversejs/dist/converse.js:64772:21
	wrappedOverride https://someserver.com/_assets/conversejs/dist/converse.js:43987:20
	apply https://someserver.com/_assets/conversejs/dist/converse.js:12950:12
	wrapper https://someserver.com/_assets/conversejs/dist/converse.js:17807:16
	jQuery.event.dispatch https://someserver.com/_assets/conversejs/dist/converse.js:7339:16
	jQuery.event.add/elemData.handle https://someserver.com/_assets/conversejs/dist/converse.js:7152:6

**Comment by ignatdoc** [comment]
And about error lines - locales was cut by me, so lines may be wrong

**Comment by jcbrand** [comment]
Should be fixed now. You can test the fix by making a new build by running `make dist` inside a clone of this repo and then using the converse.js file in the `/dist/` directory.

**Comment by ignatdoc** [comment]
OTR seems to work on new build! Thanks

**Comment by ignatdoc** [comment]
Still have problems with OTR and key generation when starting new encrypted conversation. Trying to catch an error now.

**Comment by ignatdoc** [comment]
One more problem: conversation may be started, but it will not show up a window! So you can't see messages, counters of unread and etc. This is very serious bug...
