### ISSUE TITLE
converse.js : embeded chat room example not working

### ISSUE THREAD

**Issue by sinsharat** [jcbrand/converse.js#861]
The embeded chat room example seems to be broken.

https://conversejs.org/demo/embedded.html

**Comment by jcbrand** [comment]
Looks fine to me, except that icons are not showing. What are you seeing?

**Comment by sinsharat** [comment]
ok. now it seems fine.Don't know that time it was not at all displaying the chat window.

**Comment by jcbrand** [comment]
Icons are now fixed as well

**Comment by tsankuanglee** [comment]
I'm still getting the following errors in Chrome.

`Could not find optional dependency "converse-controlbox" for the plugin "converse-muc". If it's needed, make sure it's loaded by require.js

converse-muc-embedded.min.js:210 Error: Plugin "converse-muc" tried to override ControlBoxView but it's not found.`

**Comment by jcbrand** [comment]
That's fine. The ControlBoxView is not being used for the embedded example.

**Comment by tsankuanglee** [comment]
Actually that example doesn't work -- I cannot submit my message. Like this:
http://imgur.com/T9OmhJ4

**Comment by jcbrand** [comment]
Oh, sorry, I didn't notice that.

I don't think it's related to the converse-controlbox error though. That shouldn't be an error really, just a warning.

**Comment by tsankuanglee** [comment]
All good. Thank you!
