### ISSUE TITLE
version 3.3.1 from cdn not working on IE 11, color: maroon not found

### ISSUE THREAD

**Issue by henkdemarie** [jcbrand/converse.js#995]
after initializing converse in I.E. 11 i get:
<code>%c ERROR: Not Found color: maroon</code>
Then, when i try to log in i get
<code>%c FATAL: TypeError: De eigenschap of methode replaceWith wordt niet ondersteund door dit object
   at sortAndPositionAllItems (https://cdn.conversejs.org/dist/converse.js:50232:7)
   at triggerEvents (https://cdn.conversejs.org/dist/converse.js:36106:32)
   at triggerApi (https://cdn.conversejs.org/dist/converse.js:36091:19)
   at eventsApi (https://cdn.conversejs.org/dist/converse.js:35890:7)
   at Events.trigger (https://cdn.conversejs.org/dist/converse.js:36081:5)
   at _onModelEvent (https://cdn.conversejs.org/dist/converse.js:36922:7)
   at triggerEvents (https://cdn.conversejs.org/dist/converse.js:36107:33)
   at triggerApi (https://cdn.conversejs.org/dist/converse.js:36092:22)
   at eventsApi (https://cdn.conversejs.org/dist/converse.js:35890:7)
   at Events.trigger (https://cdn.conversejs.org/dist/converse.js:36081:5) color: maroon
%c FATAL: error: De eigenschap of methode replaceWith wordt niet ondersteund door dit object color: maroon</code>

The dutch error message says: method or property replaceWith not supported by this object

**Comment by jcbrand** [comment]
Thanks for reporting.

I committed a fix. Can you please check with [this build](https://cloud.opkode.com/index.php/s/RYCJkTw2orQhGGx/download) whether the problem is now solved?

**Comment by henkdemarie** [comment]
Thank you very much for your effort.

And sorry for the late reply, i have been "out of the office" for some days.
At work im still receiving the same errors with this build.
Will try at home to see if its ie11, or some settings at work (wich im not
allowed to change)
Thanks

Kind regards,

Henk de Marie

**Comment by jcbrand** [comment]
Hi Henk

I downloaded a Virtual Machine and tested it myself. From what I can tell the problem is solved now (after fixing more bugs).
